export const fallbackCountries = [
  {
    name: { common: 'Japan', official: 'Japan' },
    cca2: 'JP',
    cca3: 'JPN',
    capital: ['Tokyo'],
    region: 'Asia',
    subregion: 'Eastern Asia',
    population: 125416877,
    area: 377975,
    flags: { svg: 'https://flagcdn.com/jp.svg', alt: 'Flag of Japan' },
    coatOfArms: {},
    languages: { jpn: 'Japanese' },
    currencies: { JPY: { name: 'Japanese yen', symbol: '¥' } },
    timezones: ['UTC+09:00'],
    continents: ['Asia'],
    borders: [],
    maps: { googleMaps: 'https://goo.gl/maps/NGTLSCSrA8bMrvnX9' },
    latlng: [36, 138],
    capitalInfo: { latlng: [35.68, 139.75] },
    independent: true,
    unMember: true,
  },
  {
    name: { common: 'France', official: 'French Republic' },
    cca2: 'FR',
    cca3: 'FRA',
    capital: ['Paris'],
    region: 'Europe',
    subregion: 'Western Europe',
    population: 67391582,
    area: 551695,
    flags: { svg: 'https://flagcdn.com/fr.svg', alt: 'Flag of France' },
    coatOfArms: {},
    languages: { fra: 'French' },
    currencies: { EUR: { name: 'Euro', symbol: '€' } },
    timezones: ['UTC-10:00', 'UTC-09:30', 'UTC-09:00', 'UTC-08:00', 'UTC-04:00', 'UTC+01:00'],
    continents: ['Europe'],
    borders: ['AND', 'BEL', 'DEU', 'ITA', 'LUX', 'MCO', 'ESP', 'CHE'],
    maps: { googleMaps: 'https://goo.gl/maps/g7QxxSFsWyTPKuzd7' },
    latlng: [46, 2],
    capitalInfo: { latlng: [48.87, 2.33] },
    independent: true,
    unMember: true,
  },
  {
    name: { common: 'Brazil', official: 'Federative Republic of Brazil' },
    cca2: 'BR',
    cca3: 'BRA',
    capital: ['Brasília'],
    region: 'Americas',
    subregion: 'South America',
    population: 212559409,
    area: 8515767,
    flags: { svg: 'https://flagcdn.com/br.svg', alt: 'Flag of Brazil' },
    coatOfArms: {},
    languages: { por: 'Portuguese' },
    currencies: { BRL: { name: 'Brazilian real', symbol: 'R$' } },
    timezones: ['UTC-05:00', 'UTC-04:00', 'UTC-03:00', 'UTC-02:00'],
    continents: ['South America'],
    borders: ['ARG', 'BOL', 'COL', 'GUF', 'GUY', 'PRY', 'PER', 'SUR', 'URY', 'VEN'],
    maps: { googleMaps: 'https://goo.gl/maps/waCKk21HeeqFzkNC9' },
    latlng: [-10, -55],
    capitalInfo: { latlng: [-15.79, -47.88] },
    independent: true,
    unMember: true,
  },
  {
    name: { common: 'Georgia', official: 'Georgia' },
    cca2: 'GE',
    cca3: 'GEO',
    capital: ['Tbilisi'],
    region: 'Asia',
    subregion: 'Western Asia',
    population: 3714000,
    area: 69700,
    flags: { svg: 'https://flagcdn.com/ge.svg', alt: 'Flag of Georgia' },
    coatOfArms: {},
    languages: { kat: 'Georgian' },
    currencies: { GEL: { name: 'lari', symbol: '₾' } },
    timezones: ['UTC+04:00'],
    continents: ['Asia'],
    borders: ['ARM', 'AZE', 'RUS', 'TUR'],
    maps: { googleMaps: 'https://goo.gl/maps/bvCaGBePR1ZEDK5cA' },
    latlng: [42, 43.5],
    capitalInfo: { latlng: [41.68, 44.83] },
    independent: true,
    unMember: true,
  },
  {
    name: { common: 'Canada', official: 'Canada' },
    cca2: 'CA',
    cca3: 'CAN',
    capital: ['Ottawa'],
    region: 'Americas',
    subregion: 'North America',
    population: 38005238,
    area: 9984670,
    flags: { svg: 'https://flagcdn.com/ca.svg', alt: 'Flag of Canada' },
    coatOfArms: {},
    languages: { eng: 'English', fra: 'French' },
    currencies: { CAD: { name: 'Canadian dollar', symbol: '$' } },
    timezones: ['UTC-08:00', 'UTC-07:00', 'UTC-06:00', 'UTC-05:00', 'UTC-04:00', 'UTC-03:30'],
    continents: ['North America'],
    borders: ['USA'],
    maps: { googleMaps: 'https://goo.gl/maps/jmEVLugreeqiZXxbA' },
    latlng: [60, -95],
    capitalInfo: { latlng: [45.42, -75.7] },
    independent: true,
    unMember: true,
  },
  {
    name: { common: 'Australia', official: 'Commonwealth of Australia' },
    cca2: 'AU',
    cca3: 'AUS',
    capital: ['Canberra'],
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    population: 25687041,
    area: 7692024,
    flags: { svg: 'https://flagcdn.com/au.svg', alt: 'Flag of Australia' },
    coatOfArms: {},
    languages: { eng: 'English' },
    currencies: { AUD: { name: 'Australian dollar', symbol: '$' } },
    timezones: ['UTC+05:00', 'UTC+06:30', 'UTC+07:00', 'UTC+08:00', 'UTC+09:30', 'UTC+10:00'],
    continents: ['Oceania'],
    borders: [],
    maps: { googleMaps: 'https://goo.gl/maps/DcjaDa7UbhnZTndH6' },
    latlng: [-27, 133],
    capitalInfo: { latlng: [-35.27, 149.13] },
    independent: true,
    unMember: true,
  },
  {
    name: { common: 'Morocco', official: 'Kingdom of Morocco' },
    cca2: 'MA',
    cca3: 'MAR',
    capital: ['Rabat'],
    region: 'Africa',
    subregion: 'Northern Africa',
    population: 36910558,
    area: 446550,
    flags: { svg: 'https://flagcdn.com/ma.svg', alt: 'Flag of Morocco' },
    coatOfArms: {},
    languages: { ara: 'Arabic', ber: 'Berber' },
    currencies: { MAD: { name: 'Moroccan dirham', symbol: 'د.م.' } },
    timezones: ['UTC+00:00'],
    continents: ['Africa'],
    borders: ['DZA', 'ESH', 'ESP'],
    maps: { googleMaps: 'https://goo.gl/maps/6oMv3dyBZg3iaXQ5A' },
    latlng: [32, -5],
    capitalInfo: { latlng: [34.02, -6.82] },
    independent: true,
    unMember: true,
  },
  {
    name: { common: 'United States', official: 'United States of America' },
    cca2: 'US',
    cca3: 'USA',
    capital: ['Washington, D.C.'],
    region: 'Americas',
    subregion: 'North America',
    population: 329484123,
    area: 9372610,
    flags: { svg: 'https://flagcdn.com/us.svg', alt: 'Flag of the United States' },
    coatOfArms: {},
    languages: { eng: 'English' },
    currencies: { USD: { name: 'United States dollar', symbol: '$' } },
    timezones: ['UTC-12:00', 'UTC-11:00', 'UTC-10:00', 'UTC-09:00', 'UTC-08:00', 'UTC-07:00', 'UTC-06:00', 'UTC-05:00'],
    continents: ['North America'],
    borders: ['CAN', 'MEX'],
    maps: { googleMaps: 'https://goo.gl/maps/e8M246zY4BSjkjAv6' },
    latlng: [38, -97],
    capitalInfo: { latlng: [38.89, -77.05] },
    independent: true,
    unMember: true,
  },
  {
    name: { common: 'Italy', official: 'Italian Republic' },
    cca2: 'IT',
    cca3: 'ITA',
    capital: ['Rome'],
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 59554023,
    area: 301336,
    flags: { svg: 'https://flagcdn.com/it.svg', alt: 'Flag of Italy' },
    coatOfArms: {},
    languages: { ita: 'Italian' },
    currencies: { EUR: { name: 'Euro', symbol: '€' } },
    timezones: ['UTC+01:00'],
    continents: ['Europe'],
    borders: ['AUT', 'FRA', 'SMR', 'SVN', 'CHE', 'VAT'],
    maps: { googleMaps: 'https://goo.gl/maps/8M1K27TDj7StTRTq8' },
    latlng: [42.83, 12.83],
    capitalInfo: { latlng: [41.9, 12.48] },
    independent: true,
    unMember: true,
  },
  {
    name: { common: 'New Zealand', official: 'New Zealand' },
    cca2: 'NZ',
    cca3: 'NZL',
    capital: ['Wellington'],
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    population: 5084300,
    area: 270467,
    flags: { svg: 'https://flagcdn.com/nz.svg', alt: 'Flag of New Zealand' },
    coatOfArms: {},
    languages: { eng: 'English', mri: 'Māori', nzs: 'New Zealand Sign Language' },
    currencies: { NZD: { name: 'New Zealand dollar', symbol: '$' } },
    timezones: ['UTC-11:00', 'UTC-10:00', 'UTC+12:00', 'UTC+12:45', 'UTC+13:00'],
    continents: ['Oceania'],
    borders: [],
    maps: { googleMaps: 'https://goo.gl/maps/xXiDQo65dwdpw9iu8' },
    latlng: [-41, 174],
    capitalInfo: { latlng: [-41.3, 174.78] },
    independent: true,
    unMember: true,
  },
  {
    name: { common: 'South Africa', official: 'Republic of South Africa' },
    cca2: 'ZA',
    cca3: 'ZAF',
    capital: ['Pretoria', 'Bloemfontein', 'Cape Town'],
    region: 'Africa',
    subregion: 'Southern Africa',
    population: 59308690,
    area: 1221037,
    flags: { svg: 'https://flagcdn.com/za.svg', alt: 'Flag of South Africa' },
    coatOfArms: {},
    languages: { afr: 'Afrikaans', eng: 'English', nbl: 'Southern Ndebele', nso: 'Northern Sotho', sot: 'Southern Sotho', ssw: 'Swazi', tsn: 'Tswana', tso: 'Tsonga', ven: 'Venda', xho: 'Xhosa', zul: 'Zulu' },
    currencies: { ZAR: { name: 'South African rand', symbol: 'R' } },
    timezones: ['UTC+02:00'],
    continents: ['Africa'],
    borders: ['BWA', 'LSO', 'MOZ', 'NAM', 'SWZ', 'ZWE'],
    maps: { googleMaps: 'https://goo.gl/maps/CLCZ1R8Uz1KpYhRv6' },
    latlng: [-29, 24],
    capitalInfo: { latlng: [-25.7, 28.22] },
    independent: true,
    unMember: true,
  },
  {
    name: { common: 'India', official: 'Republic of India' },
    cca2: 'IN',
    cca3: 'IND',
    capital: ['New Delhi'],
    region: 'Asia',
    subregion: 'Southern Asia',
    population: 1380004385,
    area: 3287590,
    flags: { svg: 'https://flagcdn.com/in.svg', alt: 'Flag of India' },
    coatOfArms: {},
    languages: { eng: 'English', hin: 'Hindi', tam: 'Tamil' },
    currencies: { INR: { name: 'Indian rupee', symbol: '₹' } },
    timezones: ['UTC+05:30'],
    continents: ['Asia'],
    borders: ['BGD', 'BTN', 'MMR', 'CHN', 'NPL', 'PAK'],
    maps: { googleMaps: 'https://goo.gl/maps/WSk3fLwG4vtPQetp7' },
    latlng: [20, 77],
    capitalInfo: { latlng: [28.6, 77.2] },
    independent: true,
    unMember: true,
  },
];

export const getFallbackCountryByCode = (code) =>
  fallbackCountries.find((country) => country.cca3 === code || country.cca2 === code);
